Feature/aesthetic async2
mahdiguermache/transition pull request #8
Opened 2023-04-06 13:12 UTC by Wassim27

Aesthetic lines algorythm doesn't slow down the client anymore :
Usage of async.
Usage of promises.
Usage of the timeout() function.

2023-04-10 20:20 UTC, nik498 approved these changes

2023-04-11 16:59 UTC, GabrielBruno24 approved these changes

2023-04-11 19:16 UTC, tahini requested changes
Ok, ça ne devrait plus bloquer le client, le code rend le contrôle à intervalles réguliers, c'est parfait.

2023-04-11 19:16 UTC, tahini commented on packages/chaire-lib-common/src/services/geodata/ManageOverlappingLines.ts
> +    return new Promise((resolve, reject) => {
Rendu à cette ligne, vous avez déjà attendu après findOverlapingLines et applyOffset avec le await, faites juste retourner `geojson` (ou gardez le `return cleanLines` d'avant)

2023-04-11 19:16 UTC, tahini commented on packages/chaire-lib-common/src/services/geodata/ManageOverlappingLines.ts
> +        const features = layerData.features as any;
features sont des LineString, ce serait mieux de ne pas caster as any

2023-04-11 19:16 UTC, tahini commented on packages/chaire-lib-common/src/services/geodata/ManageOverlappingLines.ts
> +        for (let i = 0; i < features.length - 1; i++) {
Vous pourriez faire un check de isCancelled à tous les x features (20? 30? 100?)

2023-04-11 19:16 UTC, tahini commented on packages/chaire-lib-common/src/services/geodata/ManageOverlappingLines.ts
> +    overlap: any,
Serait-il possible de typer correctement overlap et features? Features est un array de LineString je pense

2023-04-11 19:16 UTC, tahini commented on packages/chaire-lib-common/src/services/geodata/ManageOverlappingLines.ts
> +        for (let i = 0; i < overlapArray.length; i++) {
Idem ici, le isCancelled peut être testé tous les X features, à moins qu'il n'y ait pas trop de segments? Mais je pense que tous les overlaps passent ici, non?

2023-04-11 19:16 UTC, tahini commented on packages/transition-frontend/src/components/map/TransitionMainMap.tsx
> +            manageOverlappingLines(geojson as GeoJSON.FeatureCollection<GeoJSON.LineString>,false).then((layerData) => {
Ajouter un TODO ici pour implémenter l'annulation de l'opération.

2023-04-14 12:47 UTC, florencelauer approved these changes

2023-04-14 14:48 UTC, merged